services:
  dns:
    container_name: dns
    image: cytopia/bind:stable-manifest-linux-amd64
    ports:
    - 53:53/udp
    - 53:53/tcp
    environment:
      DNS_A: |
        *.apps.ocpprod.pjedomex.gob.mx=10.22.249.7,
        *.openshift.pjedomex.mx=10.22.249.7
      DNS_FORWARDER: 8.8.8.8,8.8.4.4
      ALLOW_QUERY: 0.0.0.0/0
      ALLOW_RECURSION: 0.0.0.0/0